### ISSUE TITLE
Auto-destroy worthless doesn't destroy unsellable junk

### ISSUE THREAD

**Issue by t2YU2m8l83** [klingo/ESO-PersonalAssistant#224]
All those worthless login bonuses are flooding my inventory but even if I mark them as junk, they'll never be destroyed automatically. The option to auto destroy worthless junk should also include items like those rewards or known motives, simply everything that can't be sold but is marked as junk should be destroyed.

**Comment by klingo** [comment]
Currently, the auto-destroy only works for stolen items - that's why your daily login bonuses are not getting directly destroyed.
In addition, the auto-destroy currently only works if the addon marks an item as junk, but not if the "mark as junk" is done by the player; thus I explicitely excluded e.g. motives because the addon would not know if it is a cheap motif, or one that is worth 10k+ gold. But if you anyway mark them manually as junk; why not use the "destroy item" keybinding? :)

What I will look into:
- [ ] Add option to also auto-destroy non-stolen items (e.g. dailly login rewards)

**Comment by t2YU2m8l83** [comment]
The point of your addon is to no longer care about specific things. Some event styles are worthless and if you do the event, you receive dozens of them. Therefore I want to able to mark them as junk and they should permanently be destroyed up on pickup if they can't be sold. The keybinding to destroy it simply isn't enough if I receive it every couple of minutes.

**Comment by klingo** [comment]
More time needed for additional translations --> shifted to 2.4.19
