### ISSUE TITLE
Prioritize junk rules before Crafting Bag

### ISSUE THREAD

**Issue by t2YU2m8l83** [klingo/ESO-PersonalAssistant#236]
I receive a lot of lower level materials from the crafting dailys that are worthless for me. I already added junk rules for those items but the crafting bag grabs them before your addon can move them to the junk items section.

**Comment by klingo** [comment]
If I remember correctly, even when your inventory is completely full (0 free slots) you can still loot crafting materials as ESO Plus member. This would mean that crafting materials directly go to the Craft Bag where they cannot be marked as junk or sold or destroyed.

Would you be willing to verify above, if you indeed still can loot crafting materials when your inventory is full?

**Comment by t2YU2m8l83** [comment]
Yes, it is possible to loot things with a full inventory, if they are valid for the crafting bag. But your addon simply has to check the crafting bag upon opening a shop, retrieve the items from the perma junk rule and sell them.

**Comment by klingo** [comment]
This is not how PAJunk is deisgned to work. PAJunk applies action(s) when you loot/receive the items and not when you visit any merchant. Also since the Craft Bag has unlimited space, I don't see a big enough need to implement something like that - it is a very niche feature to sell stuff from the Craft Bag.
