### ISSUE TITLE
PersonalAssistant (Banking) ESO

### ISSUE THREAD

**Issue by iowann** [klingo/ESO-PersonalAssistant#370]
аддон перестал работать с алхимией почему-то. он не кладет ее в банк. перезапускал. настройки проверил

**Comment by iowann** [comment]
не работает только на одном персонаже. видимо у меня проблема

**Comment by iowann** [comment]
в общем, в чем проблема:
данный аддон имеет возможность работать с DolgubonsLazyWritCreator и не убирать в банк нужные для задания предметы, но программа так написана, что если у тебя задание на Алхимию(как было у меня), и есть не все нужное количество, то аддон не убирает в банк вообще все ингредиенты для алхимии. как по мне это ошибка/недоработка

**Comment by klingo** [comment]
DolgubonsLazyWritCreator does not provide any information what kind of writs you have and whether there are items on the bank for that. It only tells that you have **any** writs and that you have enabled the auto-withdraw from the bank. And since DolgubonsLazyWritCreator also automatically closes the bank again, the best I could imlement is to just avoid any transfers when DolgubonsLazyWritCreator tells there are active writs.

**Comment by iowann** [comment]
oh, ok, sorry
thanks for the answer, I will know)
